STATUS_PENDING = "PENDING"
STATUS_ACTIVE = "ACTIVE"
STATUS_ORPHANED = "ORPHANED"

STATUS_CHOICES = [
    (STATUS_PENDING, "Pending upload"),
    (STATUS_ACTIVE, "Confirmed / in use"),
    (STATUS_ORPHANED, "Orphaned / no longer needed"),
]

SERVICE_TYPE_PROFILE = "PROFILE"
SERVICE_TYPE_ACCOUNT = "ACCOUNT"
SERVICE_TYPE_DOCUMENTS = "DOCUMENTS"

SERVICE_TYPES = [
    (SERVICE_TYPE_PROFILE, "Profile images"),
    (SERVICE_TYPE_ACCOUNT, "User-generated content / posts"),
    (SERVICE_TYPE_DOCUMENTS, "PDFs, certificates, forms"),
]
