# Generated by Django 5.2.11 on 2026-02-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
