# Generated by Django 5.2.11 on 2026-02-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_service', '0002_remove_ownerprofile_location_petprofile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petprofile',
            name='species',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='type',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Rabbit', 'Rabbit'), ('Bird', 'Bird'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
