# Generated by Django 5.2.11 on 2026-02-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_service', '0003_remove_petprofile_species_petprofile_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petprofile',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='province',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='type',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('RAB', 'Rabbit'), ('BRD', 'Bird'), ('OTH', 'Other')], default='OTH', max_length=30),
        ),
    ]
