# Generated by Django 5.2.11 on 2026-03-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_service', '0004_rename_location_petprofile_city_petprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='petprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='status',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active')], default='ONBOARDING', max_length=10),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='status',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active')], default='ONBOARDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='country',
            field=models.CharField(default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('RAB', 'Rabbit'), ('BRD', 'Bird'), ('OTH', 'Other')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='petprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ONBOARDING')), fields=('owner_profile',), name='unique_onboarding_pet_per_owner'),
        ),
    ]
