STATUS_ACTIVE = "ACTIVE"
STATUS_DELETED = "DELETED"

STATUS_CHOICES = [
    (STATUS_ACTIVE, "Active"),
    (STATUS_DELETED, "Deleted"),
]

VISIBILITY_PUBLIC = "PUBLIC"
VISIBILITY_FRIENDS = "FRIENDS"
VISIBILITY_PRIVATE = "PRIVATE"

VISIBILITY_CHOICES = [
    (VISIBILITY_PUBLIC, "Public"),
    (VISIBILITY_FRIENDS, "Friends"),
    (VISIBILITY_PRIVATE, "Private"),
]
