# Generated by Django 5.2.11 on 2026-03-01 03:51

import media_service.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('profile', 'Profile images'), ('account', 'User-generated content / posts'), ('documents', 'PDFs, certificates, forms')], help_text='Type/category of the media (profile, account, documents)', max_length=50)),
                ('owner_id', models.UUIDField(help_text='ID of the entity (owner) that owns this file')),
                ('pet_id', models.UUIDField(blank=True, help_text='ID of the pet (optional, only for pet images)', null=True)),
                ('file', models.FileField(help_text='File stored in S3', upload_to=media_service.models.UploadToPath(base_folder='media'))),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_type', 'owner_id', 'pet_id'], name='media_files_service_d2cca8_idx')],
            },
        ),
    ]
