# Generated by Django 5.2.11 on 2026-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending upload'), ('active', 'Confirmed / in use'), ('orphaned', 'Orphaned / no longer needed')], default='pending', help_text='Upload status of the file', max_length=20),
        ),
    ]
