# Generated by Django 5.2.12 on 2026-03-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0002_mediafile_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mediafile',
            name='media_files_service_d2cca8_idx',
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='owner_id',
            new_name='owner_profile_id',
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='pet_id',
            new_name='pet_profile_id',
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='service_type',
            field=models.CharField(choices=[('PROFILE', 'Profile images'), ('ACCOUNT', 'User-generated content / posts'), ('DOCUMENTS', 'PDFs, certificates, forms')], help_text='Type/category of the media (PROFILE, ACCOUNT, DOCUMENTS)', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending upload'), ('ACTIVE', 'Confirmed / in use'), ('ORPHANED', 'Orphaned / no longer needed')], default='PENDING', help_text='Upload status of the file', max_length=20),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['service_type', 'owner_profile_id', 'pet_profile_id'], name='media_files_service_3b9a07_idx'),
        ),
    ]
