# Generated by Django 5.2.12 on 2026-04-04 21:03

import media_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0003_remove_mediafile_media_files_service_d2cca8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(help_text='File stored in S3', max_length=512, upload_to=media_service.models.UploadToPath(base_folder='media')),
        ),
    ]
